apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: main-app
      version: '0.0.x'
      sourceRef:
        kind: HelmRepository
        name: universal
        namespace: default
      interval: 1m
  valuesFrom:
  - chartFileRef:
      path: ./apps/helm/values.yaml
      optional: true
