apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: main-app
      version: '0.0.x'
      sourceRef:
        kind: HelmRepository
        name: universal
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
