apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argocd-test
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/alexandershelega/argocd-test.git
