apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: argocd-test
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/alexandershelega/argocd-test.git
  ref:
    branch: main
  secretRef:
    name: githib-auth
