apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: universal
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.com/api/v4/projects/33385052/packages/helm/main
  secretRef:
    name: helm-auth
